apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-deployment
spec: 
  replicas: 3
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
        - name: todo-app
          image: itshirdeshk/todo-app:latest
          ports: 
            - containerPort: 8080
      imagePullSecrets:
        - name: dockerhub-secret