version: '3.8'

services:
  backend:
    build: .
    container_name: todo-app
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
    networks:
      - todo-network
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27107:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - todo-network
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "password"]
    volumes:
      - redis-data:/data
    networks:
      - todo-network

volumes:
  mongo-data:
  redis-data:

networks:
  todo-network